import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Sanatan Dharm कला ( kalaa )",
  description: "Generated by create next app",
  verification: {
    google: "LdDoFkVB5VrpSPJQw13BXnd_NxilRfUZA1NskNbwwG0",
  },
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        <meta
          name="p:domain_verify"
          content="8590f2f69cfa342f22e3e663acc8f66"
        />
      </head>

      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}